### ISSUE TITLE
fix[type specs component]: inline code snippet incorrect

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/gatsby-theme-carbon#1108]
## fix[type specs component]: inline code snippet incorrect

The background of the inline code snippet is displaying as white (on a white background); it looks bad and doesn't prompt users to interact with it.

**Incorrect behavior**

![image](https://user-images.githubusercontent.com/43144260/112553456-8a4d5e80-8d92-11eb-9623-672c3ed12b18.png)

<br>

**Correct behavior (G20, $ui-03 background)**

![image](https://user-images.githubusercontent.com/43144260/112553505-a3560f80-8d92-11eb-9b14-629f358ee894.png)

**Comment by vpicone** [comment]
@jeanservaas It looks like this was resolved by some upstream Carbon changes, can you confirm it's correct in production?
![Screen Shot 2021-08-23 at 4.14.34 PM.png](https://images.zenhubusercontent.com/5deea65833c75ca22dbfaca3/fa7bf19c-34fb-4dfc-a511-ce88d54903b5)

**Comment by alisonjoseph** [comment]
Looks like its still an issue on IDL website only. https://www.ibm.com/design/language/typography/type-specs-ui
