### ISSUE TITLE
Tabs on component pages have incorrect paths

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/gatsby-theme-carbon#20]
### The Problem
If you have a `pathPrefix` (i.e., https://www.gatsbyjs.org/docs/path-prefix/), then generated paths for component page tabs are incorrect. See here: https://jendowns.github.io/gatsby-theme-carbon/components/accordion/code (make sure there's no trailing slash, otherwise `currentTab` is empty 😬 )

So all of your tab paths on component pages will 404.

### Testing Instructions

To demonstrate this, I made a sample repo ( https://github.com/jendowns/gatsby-theme-carbon) by forking `gatsby-theme-carbon` and then did this:

* added a github pages deployment for the example site: https://github.com/jendowns/gatsby-theme-carbon/blob/master/packages/example/package.json#L10
* added a `pathPrefix` because my deployment has a subdirectory in the path: https://github.com/jendowns/gatsby-theme-carbon/blob/master/packages/example/gatsby-config.js#L2 
* added an "Accordion" test component with typical tabs front matter: https://github.com/jendowns/gatsby-theme-carbon/tree/master/packages/example/src/pages/components/accordion

**The key is that you need to deploy to an environment, like Github Pages, that has subdirectories in the path.**

**Comment by vpicone** [comment]
Hey Jen! We can (and should) have brought the path prefix in by default there, I'll check it out.

**Comment by jendowns** [comment]
@vpicone Thanks! Just wanted to point out that it looks like `pathPrefix` is being twice in two different ways... 🕵️‍♀️ 

### Scenario 1:
If you go to https://jendowns.github.io/gatsby-theme-carbon/components/accordion/code (no trailing slash), then there's no `currentTab` and all of those tab paths are structured like this:
```
https://jendowns.github.io/gatsby-theme-carbon/gatsby-theme-carbon/components/accordion/style
```
**NOTE:** if you have trouble getting to that link without a trailing slash (Firefox keeps adding it for me 😭), then just click on that **TEST - Accordion** page link directly from the sidebar.


### Scenario 2:
If you go to https://jendowns.github.io/gatsby-theme-carbon/components/accordion/code/ (with a trailing slash, which can happen incidentally when you go directly to the URL unfortunately!), then you get this structure for tab links:
```
https://jendowns.github.io/gatsby-theme-carbon/style/gatsby-theme-carbon/components/accordion/code/
```

**Comment by vpicone** [comment]
Nice thanks for the awesome test cases

**Comment by vpicone** [comment]
I believe this was fixed with v0.4 if you have a chance to test it out.

**Comment by jendowns** [comment]
Unfortunately this path bug still exists in `v0.4.0` (only for tabs on component pages) 😭

**Comment by vpicone** [comment]
I’m pretty sure I know what’s up. Hoping to get this out tomorrow.
