### ISSUE TITLE
[Type] Intro paragraph seems too big and leading too tight

### ISSUE THREAD

**Issue by sadekbazaraa** [carbon-design-system/gatsby-theme-carbon#498]
The intro paragraph type scale seems off. The size and leading should be the same between the intro paragraph and anchor links and they appear differently.

See example here:
https://www.carbondesignsystem.com/guidelines/accessibility/overview

![Screen Shot 2019-11-05 at 4 40 23 PM](https://user-images.githubusercontent.com/33162280/68249512-fe943000-ffec-11e9-81dc-ecb524de97ba.png)

Here is another example comparing the live brand center site (bottom) with my Sketch file (top). You can see that the intro paragraph is slightly smaller and more open in the Sketch file.
https://www.ibm.com/brand/architecture

![Screen Shot 2019-11-05 at 1 18 54 PM](https://user-images.githubusercontent.com/33162280/68249553-12d82d00-ffed-11e9-9685-cedd2aa01fc3.png)

@vpicone 
FYI @mjabbink

**Comment by vpicone** [comment]
@sadekbazaraa great eye, I think this is a carbon website issue though. That page was using an `h3` instead of the new `PageDescription` component. Looking more into it, there were ~34 other pages that were also using `h3`s. I opened https://github.com/carbon-design-system/carbon-website/pull/692 to fix it.

Could you elaborate a little bit on what's wrong with Brand? I'm not sure what component their using

**Comment by sadekbazaraa** [comment]
@vpicone it was the same issue on brand, I was just pointing out the same issue there.

**Comment by alisonjoseph** [comment]
I believe this has been fixed w/ Vince's PR?? Feel free to reopen if I missed something

**Comment by sadekbazaraa** [comment]
@alisonjoseph I just checked the live Gatsby theme sites IDL, BC, Carbon and still see the same issue that's documented at the beginning of this thread which discusses the line spacing between the intro paragraph and anchor links which should be consistent.
