### ISSUE TITLE
Ordered list is not aligned to the grid

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/gatsby-theme-carbon#720]
This screenshot shows how the ordered list are rendered outside of the grid.

May need to override `left` on `.bx--list--ordered:not(.bx--list--nested) > .bx--list__item::before` to be `-1rem`?

![image](https://user-images.githubusercontent.com/1691245/74171212-cc99f780-4bf3-11ea-8f90-d6b4deba01d9.png)

**Comment by jnm2377** [comment]
@peter-garvin is this alignment intentional? For some reason I thought it was since no one brought it up the last time I worked on lists, but I may be wrong.

**Comment by mjabbink** [comment]
![Screen Shot 2020-02-12 at 9.57.54 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/c4340419-3cb8-42ea-9029-1ff55440a3d3)

**Comment by mjabbink** [comment]
@jeanservaas can you provide @jnm2377 so we can get this resolved. It’s been wrong for months and effecting all Gatsby theme sites. It not good and therefore it’s severity 2.

**Comment by sstrubberg** [comment]
@jnm2377 when I inspect the production sites of Carbon, w3, and IDL, I see ::before pseudo elements dictating the placement of the OLs inherited from Carbon Core, but when I launch the GatsbyTheme in a dev environment the pseudo elements disappear.

**Comment by sstrubberg** [comment]
@vpicone When Josephina and I adjusted the margin-left on the <li> on the carbon-site, it looks great, but when we adjust the exact same values on the GatsbyTheme, it looks bad. Josephina mentioned a time where the FeatureCard was working with the Theme and not on the Carbon site. Something is :🐟-y here.

**Comment by sstrubberg** [comment]
Resolved with this [PR](https://github.com/carbon-design-system/carbon-website/pull/949)

**Comment by vpicone** [comment]
This is still an issue in master: https://gatsby-theme-carbon.now.sh/demo#header-again

**Comment by sstrubberg** [comment]
Yeah, i got my wires crossed. The PR i listed above has nothing to do with this issue. Working on it now!
